name: Testing Release

on:
  push:
    tags:
      - '*'

jobs:

  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: sudo apt update && sudo apt install meld build-essential libncurses5-dev bison flex gcc-aarch64-linux-gnu libelf-dev -y

    - name: Build x64 kernel
      run: ./build.sh -nka x64
      shell: bash
    
    - name: Save distribution files
      uses: actions/upload-artifact@v2
      with:
        name: distribution-files
        path: dist
        retention-days: 1
  
  
  release:
    needs: build
    
    runs-on: ubuntu-22.04
    
    steps:
    - name: Download distribution files
      uses: actions/download-artifact@v2
    
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: |
          ${{ github.event.head_commit.message }}
        draft: false
        prerelease: false
    
    - name: Upload x64 kernel
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./distribution-files/bzImage
        asset_name: bzImage
