name: Testing Release

on:
  push:
    tags:
      - '*'

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: sudo apt update && sudo apt install meld build-essential libncurses5-dev bison flex gcc-aarch64-linux-gnu libelf-dev -y

    - name: Build x64 kernel
      run: ./build.sh -nka x64
      shell: bash
    
    - name: Save distribution files
      uses: actions/upload-artifact@v2
      with:
        name: distribution-files
        path: dist
        retention-days: 1
  
  
  release:
    needs: build
    
    runs-on: ubuntu-latest
    
    steps:
    - name: Download distribution files
      uses: actions/download-artifact@v2
      
    - name: Create Relese
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: ./distribution-filese/bzImage
