name: Testing Release

on:
  workflow_dispatch:
    inputs:
      release_name:
        type: string
        description: 'Release Name'
        required: true
      relese_description:
        type: string
        description: 'Release Description'
        required: false
      tag_name:
        type: string
        description: 'Tag Name'
        required: true
        
  
jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: sudo apt update && sudo apt install meld build-essential libncurses5-dev bison flex gcc-aarch64-linux-gnu libelf-dev -y

    - name: Build x64 kernel
      run: ./build.sh -nka x64
      shell: bash
    
    - name: Save distribution files
      uses: actions/upload-artifact@v2
      with:
        name: distribution-files
        path: dist
        retention-days: 1
  
  
  release:
    needs: build
    
    runs-on: ubuntu-latest
    
    steps:
    - name: Download distribution files
      uses: actions/download-artifact@v2
      
    - name: Create release
      uses: softprops/action-gh-release@v1
      with:
        name: ${{ github.event.inputs.release_name }}
        body: ${{ github.event.inputs.relese_description }}
        tag_name: ${{ github.event.inputs.tag_name }}
        files: ./distribution-files/bzImage
