name: Add USB Image to Release

on:
  release:
    types:
      - released

jobs:
  add-usb-image:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create USB Image
        run: |
            sudo apt-get install grub-efi-amd64 parted kpartx
            sudo ./create-usb-image.sh "https://github.com/${{github.repository}}/releases/download/${{ github.event.release.tag_name }}" 

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: /tmp/fos-usb.img
