name: Test Creating Release

on:
  workflow_dispatch:
    inputs:
      release_name:
        type: string
        description: "Release Name"
        required: true
      tag_name:
        type: string
        description: "Tag Name"
        required: true
      is_prerelease:
        type: boolean
        default: false
        description: "Pre-release?"
        required: true
      linux_kernel_version:
        type: string
        description: "Linux kernel version"
        required: true
      buildroot_version:
        type: string
        description: "Buildroot version"
        required: true
      extra_description:
        type: string
        description: "Description"
        required: false

jobs:
  testing_sha256:
    runs-on: ubuntu-latest

    steps:
      - name: Create text file
        run: echo "testing" > test.txt
        shell: bash

      - name: Create sha256 from text file
        run: sha256sum test.txt > test.sha256
        shell: bash

      - name: Create second text file
        run: echo "testing 2" > another_test.txt
        shell: bash

      - name: Create second sha256 from text file
        run: sha256sum another_test.txt > another_test.sha256
        shell: bash

      - name: Check sha256
        run: |
          sha256sum -c ./*.sha256
          if [[ $? -ne 0 ]]; then exit 1; fi
        shell: bash

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ github.event.inputs.release_name }}
          prerelease: ${{ github.event.inputs.is_prerelease }}
          body: |
            Linux kernel ${{ github.event.inputs.linux_kernel_version }}
            Buildroot ${{ github.event.inputs.buildroot_version }}
            ${{ github.event.inputs.extra_description }}
          tag_name: ${{ github.event.inputs.tag_name }}
