name: Test Creating Release

on:
  workflow_dispatch:

jobs:
  testing_sha256:
    runs-on: ubuntu-latest

    steps:
      - name: Create text file
        run: echo "testing" > test.txt
        shell: bash

      - name: Create sha256 from text file
        run: sha256sum test.txt > test.sha256
        shell: bash

      - name: Create second text file
        run: echo "testing 2" > another_test.txt
        shell: bash

      - name: Create second sha256 from text file
        run: sha256sum another_test.txt > another_test.sha256
        shell: bash

      - name: Check sha256
        run: |
          sha256sum -c ./*.sha256
          if [[ $? -ne 0 ]]; then exit 1; fi
        shell: bash
