name: Test Creating Release

on:
  workflow_dispatch:

    inputs:
      release_name:
        type: string
        description: 'Release Name'
        required: true
      tag_name:
        type: string
        description: 'Tag Name'
        required: true
      is_prerelease:
        type: boolean
        default: false
        description: 'Pre-release?'
        required: true
      linux_kernel_version:
        type: string
        description: 'Linux kernel version'
        required: true
      buildroot_version:
        type: string
        description: 'Buildroot version'
        required: true
      extra_description:
        type: string
        description: "Description"
        required: false


jobs:

  testing_sha256:
    runs-on: ubuntu-latest

    steps:
    - name: Create text file
      run: echo "testing" > test.txt
      shell: bash
    
    - name: Create sha256 from text file
      run: sha256sum test.txt > test.sha256
      shell: bash
    
    - name: Check sha256
      run: |
        sha256sum -c test.sha256
        if [[ $? -ne 0 ]]; then
          echo "Checksum failed."
          exit 1
        fi 
      shell: bash
    
    - name: Make failure
      run: echo "aa" >> test.sha256
      shell: bash
    
    - name: Check sha256 (should fail)
      run: |
        sha256sum -c test.sha256
        if [[ $? -ne 0 ]]; then
          echo "Checksum failed."
          exit 1
        fi 
      shell: bash
